language: go
go:
  - tip
install:
  - go get gopkg.in/check.v1
  - go get github.com/thoj/go-ircevent
  - go get github.com/smartystreets/goconvey/convey
notifications:
  irc: chat.freenode.net#go-bot
